services:
  mongo:
    container_name: mongoDalkom
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  mongo-express:
      image: mongo-express
      restart: always
      depends_on:
        - mongo
      ports:
        - "8081:8081"